### ISSUE TITLE
How to obtain the rndc protocol format

### ISSUE THREAD

**Issue by ZXiangQAQ** [isc-projects/bind9-rndc-node#2]
Hello, I would like to understand the specific protocol format of rndc, but I cannot find the official documentation. Currently, I can only infer the format of version 1 of the protocol. Are there any formats for higher versions?

**Comment by raybellis** [comment]
Only version 1 is defined.  There is no version 2.

I've added `protocol.md` to this repository, which is a Markdown conversion of the notes I made while writing this module.
